//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodEvent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string What { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public long Phone { get; set; }
        public string Website { get; set; }
        public string Monday { get; set; }
        public string Tuesday { get; set; }
        public string Wednesday { get; set; }
        public string Thursday { get; set; }
        public string Friday { get; set; }
        public string Saturday { get; set; }
        public string Sunday { get; set; }
        public string Public_holidays { get; set; }
        public string Cost { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }
        public string Geocoded_location { get; set; }
    }
}
